name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   tag_name: ${{ github.ref == 'refs/tags/' && github.ref.replace('refs/tags/', '') }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: |
          # Define an array of operating systems and their corresponding runtimes
          os_list=( "win-x64" )
          # "linux-x64" "osx-x64" )

          # Loop through each operating system in the list
          for os in "${os_list[@]}"
          do
            # Construct the output directory name based on the OS
            output_dir="./publish/$os"

            # Run the dotnet publish command for the current OS
            dotnet publish SyntheticGenerator/SyntheticGenerator.csproj \
              --self-contained --configuration Release --runtime "$os" --output "$output_dir"

            # Print a message indicating completion for the current OS (optional)
            echo "Published for $os to: $output_dir"
          done

      - name: Publish for Windows
        run: dotnet publish SyntheticGenerator/SyntheticGenerator.csproj --self-contained --configuration Release --runtime win-x64 --output ./publish/win-x64
      - name: Publish for Linux
        run: dotnet publish SyntheticGenerator/SyntheticGenerator.csproj --self-contained --configuration Release --runtime linux-x64 --output ./publish/linux-x64
      - name: Publish for Darwin (macOS)
        run: dotnet publish SyntheticGenerator/SyntheticGenerator.csproj --self-contained --configuration Release --runtime osx-x64 --output ./publish/osx-x64

      - name: zip releases
        run: |
          cd publish/win-x64
          zip -r ../win-x64.zip .
          cd ../..
          # cd publish/linux-x64
          # zip -r linux-x64.zip .
          # cd ../..
          # cd publish/osx-x64
          # zip -r osx-x64.zip .
          # cd ../..
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./publish/win-x64.zip
            ./publish/linux-x64.zip
            ./publish/osx-x64.zip
          tag_name: ${{ github.ref_name }}
          body: ${{ github.ref_name }}
