name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OS_LIST: "win-x64 linux-x64 osx-x64 osx-arm64"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: |
          # Define an array of operating systems and their corresponding runtimes
          os_list=( $OS_LIST )

          # Loop through each operating system in the list
          for os in "${os_list[@]}"
          do
            # Construct the output directory name based on the OS
            output_dir="./publish/$os"

            # Run the dotnet publish command for the current OS
            dotnet publish SyntheticGenerator/SyntheticGenerator.csproj \
              --self-contained true --configuration Release --runtime "$os" --output "$output_dir"

            # Print a message indicating completion for the current OS (optional)
            echo "Published for $os to: $output_dir"
          done

      - name: zip releases
        run: |
          for os in $OS_LIST; do
            cd publish/$os
            zip -r ../$os.zip .
            cd ../..
          done
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./publish/win-x64.zip
            ./publish/linux-x64.zip
            ./publish/osx-x64.zip
            ./publish/osx-arm64.zip
          tag_name: ${{ github.ref_name }}
          body: ${{ github.ref_name }}
