name: ReleaseOnTag
on:
  workflow_dispatch:
#   push:
#     tags:
#       - "v*.*.*"

jobs:
    publish:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - os: windows
              runtime: win-x64
            - os: linux
              runtime: linux-x64
            - os: darwin
              runtime: osx-x64
            - os: darwin
              runtime: osx-arm64
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x
        - name: Publish for ${{ matrix.os }}
          run: dotnet publish SyntheticGenerator/SyntheticGenerator.csproj --self-contained --configuration Release --runtime ${{ matrix.runtime }} --output ./publish/${{ matrix.runtime }}
        - name: zip releases
          run: |
            cd publish/${{ matrix.runtime }}
            zip -r ../${{ matrix.runtime }}.zip .
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: |
              ./publish/${{ matrix.runtime }}.zip
            tag_name: ${{ github.ref_name }}
            body: ${{ github.ref_name }}
